In [3]:
import numpy as np

In [13]:
#printlist=["global_epsilons_old","global_epsilons","global_standardized_epsilons","global_ranges"]
#printlist=["cpf_epsilons_old","cpf_epsilons","cpf_standardized_epsilons","cpf_ranges"]
#printlist=["npf_epsilons_old","npf_epsilons","npf_standardized_epsilons","npf_ranges"]
printlist=["vtx_epsilons_old","vtx_epsilons","vtx_standardized_epsilons","vtx_ranges"]

In [14]:
for item in printlist:
    print(item)
    item_array = np.load("{}.npy".format(item))
    print(item_array)

vtx_epsilons_old
[[1.83880105e+02 1.22492611e+02 7.53515893e+01 3.73142321e+01]
 [2.48783608e-01 2.47807228e-01 2.45393891e-01 2.38162689e-01]
 [6.49129360e+00 5.27636271e+00 3.40150955e+00 1.52674530e+00]
 [4.50000000e+00 4.00000000e+00 3.00000000e+00 2.00000000e+00]
 [7.32296715e+00 5.92894622e+00 4.12574198e+00 2.45598737e+00]
 [3.91260645e+00 2.57294181e+00 1.28683750e+00 6.28971225e-01]
 [7.92240248e+00 3.43585181e+00 1.02729694e+00 1.47229149e-01]
 [1.94217319e+02 3.48579875e+01 1.09890882e+01 3.04105657e+00]
 [1.20612679e+01 5.35194203e+00 1.41602764e+00 2.08524070e-01]
 [1.94758739e+02 3.48682747e+01 1.10230477e+01 3.06077399e+00]
 [9.62192808e-01 4.99999583e-01 4.99994963e-01 4.99890030e-01]
 [4.04121747e-01 2.41010464e-01 1.30102768e-01 5.96390264e-02]]
vtx_epsilons
[[134.92836548 140.60017609 143.1604921  143.90993515]
 [  0.74624451   0.74630911   0.74631517   0.74631687]
 [  4.66542737   5.46395455   5.75750621   5.8621934 ]
 [  4.           4.           4.5          4.5  